name: Run Watchtower

on:
  push:
    branches:
      - main

jobs:
  build-office-1:
    runs-on: ubuntu-4gb-hel1-1
    steps:
      - uses: actions/checkout@v2
      - name: Build code
        run: |
          cd /home/eldar/
          ls
