name: Run Watchtower

on:
  push:
    branches:
      - main

jobs:
  build-office-1:
    runs-on: self-hosted
    steps:
      - name: Build code
        run: |
          cd /home/eldar/
          ls
