name: Run Watchtower

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build code
        run:  |
           cd /home/eldar/watchtower
           docker-compose up -d
         
        
