name: Run Watchtower

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: self-hosted
    steps:
      - name: Run docker-compose
        run:  |
           cd /home/eldar/watchtower
           docker-compose up -d
         
        
