name: Run Watchtower

on: workflow_dispatch
jobs:
  Deployment:
    runs-on: self-hosted
    steps:
      - name: Run docker-compose
        run:  |
           cd /home/eldar/watchtower
           docker-compose up -d
         
        
